CSV to Python to MySQL

1.Check connection with DB

In [3]:
import mysql.connector
from mysql.connector import Error

try:
    connection = mysql.connector.connect(host='localhost',
                                         database='learnsql',
                                         user='root',
                                         password='root')
    if connection.is_connected():
        db_Info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_Info)
        cursor = connection.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)

except Error as e:
    print("Error while connecting to MySQL", e)
finally:
    if (connection.is_connected()):
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

Connected to MySQL Server version  8.0.21
You're connected to database:  ('learnsql',)
MySQL connection is closed

2.Create a Table with required field

In [4]:
import mysql.connector
from mysql.connector import Error

try:
    connection = mysql.connector.connect(host='localhost',
                                         database='learnsql',
                                         user='root',
                                         password='root')

    mySql_Create_Table_Query = """CREATE TABLE Students ( 
                             Id int(11) NOT NULL,
                             Name varchar(30) NOT NULL,
                             Uni varchar(100) NOT NULL,
                             Age int(3) NOT NULL,
                             Dept varchar(30)) """

    cursor = connection.cursor()
    result = cursor.execute(mySql_Create_Table_Query)
    print("Students Table created successfully ")

except mysql.connector.Error as error:
    print("Failed to create table in MySQL: {}".format(error))
finally:
    if (connection.is_connected()):
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

Students Table created successfully
MySQL connection is closed

3.Insert Data From csv to DB

In [5]:
import mysql.connector
from mysql.connector import Error

import pandas as pd 
datas = pd.read_table('book2.csv',encoding="utf-8",delimiter=',')
print(datas)

row = next(datas.iterrows())
print("\n")
print(type(row))




def insertVariblesIntoTable(id, name, uni,age,dept):
    try:
        connection = mysql.connector.connect(host='localhost',
                                             database='learnsql',
                                             user='root',
                                             password='root')
        cursor = connection.cursor()
        id=id+1
        mySql_insert_query = """INSERT INTO Students (Id, Name, Uni, Age,Dept) 
                           VALUES(%s, %s, %s, %s,%s) """
        id = id+1
        recordTuple = (id, name, uni,age,dept)
        cursor.execute(mySql_insert_query, recordTuple)
        connection.commit()
        print("Record inserted successfully into Laptop table")

    except mysql.connector.Error as error:
        print("Failed to insert into MySQL table {}".format(error))

    finally:
        if (connection.is_connected()):
            cursor.close()
            connection.close()
            print("MySQL connection is closed")

for index, col in datas.iterrows():
    sno = 1
    
    Name = col['Name']
    clg = col['uni']
    Age = col['age']
    Dept = col['dept']
    insertVariblesIntoTable(sno,Name,clg,Age,Dept)

    Name     uni  age dept
0  ssara  monash   21   IT
1   cena    rmit   23   IT
2  mikel     anu   34  CSE
3     dc  monash   23   IT


<class 'tuple'>
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed

To Remove Table/Insert Time Stamp/insert manual query

In [58]:
#drop a table
'''

import mysql.connector
from mysql.connector import Error

try:
    connection = mysql.connector.connect(host='localhost',
                                         database='Electronics',
                                         user='root',
                                         password='root')

    mySql_Create_Table_Query = """drop table laptop;"""

    cursor = connection.cursor()
    result = cursor.execute(mySql_Create_Table_Query)
    print("Laptop Table removed successfully ")

except mysql.connector.Error as error:
    print("Failed to create table in MySQL: {}".format(error))
finally:
    if (connection.is_connected()):
        cursor.close()
        connection.close()
        print("MySQL connection is closed")
        
'''



#to insert 1
'''
import mysql.connector
from mysql.connector import Error
from mysql.connector import errorcode

try:
    connection = mysql.connector.connect(host='localhost',
                                         database='electronics',
                                         user='root',
                                         password='root')
    mySql_insert_query = """INSERT INTO Students (Id, Name, Uni, Age,Dept) 
                           VALUES 
                           (1, 'saran', 'vec', 21,'cse') """

    cursor = connection.cursor()
    cursor.execute(mySql_insert_query)
    connection.commit()
    print(cursor.rowcount, "Record inserted successfully into Students table")
    cursor.close()

except mysql.connector.Error as error:
    print("Failed to insert record into student table {}".format(error))

finally:
    if (connection.is_connected()):
        connection.close()
        print("MySQL connection is closed")


'''

#TimeStamp

'''

import mysql.connector
from mysql.connector import Error
from datetime import datetime

try:
    connection = mysql.connector.connect(host='localhost',
                                         database='Electronics',
                                         user='root',
                                         password='root')

    mySql_insert_query = """INSERT INTO Laptop (Id, Name, Price, Purchase_date) 
                            VALUES (%s, %s, %s, %s) """

    cursor = connection.cursor()
    current_Date = datetime.now()
    # convert date in the format you want
    formatted_date = current_Date.strftime('%Y-%m-%d %H:%M:%S')
    insert_tuple = (7, 'Acer Predator Triton', 2435, current_Date)

    result = cursor.execute(mySql_insert_query, insert_tuple)
    connection.commit()
    print("Date Record inserted successfully")

except mysql.connector.Error as error:
    connection.rollback()
    print("Failed to insert into MySQL table {}".format(error))

finally:
    if (connection.is_connected()):
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

'''

#manual entry 

'''
import mysql.connector
from mysql.connector import Error

try:
    connection = mysql.connector.connect(host='localhost',
                                         database='Electronics',
                                         user='root',
                                         password='root')

    mySql_insert_query = """INSERT INTO Students (Id, Name, Uni, Age,Dept) 
                           VALUES(%s, %s, %s, %s,%s)  """

    records_to_insert = [(4,'saran','vec', 21,'cse'),(5,'saran','vec', 21,'cse'),(6,'saran','vec', 21,'cse'),(7,'saran','vec', 21,'cse')]

    cursor = connection.cursor()
    cursor.executemany(mySql_insert_query, records_to_insert)
    connection.commit()
    print(cursor.rowcount, "Record inserted successfully into students table")

except mysql.connector.Error as error:
    print("Failed to insert record into MySQL table {}".format(error))

finally:
    if (connection.is_connected()):
        cursor.close()
        connection.close()
        print("MySQL connection is closed")


'''

Laptop Table removed successfully
MySQL connection is closed